import Head from 'next/head';
import Project from '../../components/Project';

import styles from '../../sass/pages/Projects.module.scss';

function Projects() {
  const sideProjects = [
    {
      title: 'Twitleague',
      src: '/twit.jpeg',
      description: 'Social media app',
      href: 'https://twitleague-next-js.vercel.app',
    },
    {
      title: 'Yesla',
      src: '/twit.jpeg',
      description: 'Copy of Telsa site for Frontend practice',
      href: null,
    },
  ];

  const pastProjects = [
    {
      title: 'CrowdCoin',
      src: '/twit.jpeg',
      description: 'Decentralized Kickstarter dapp',
      href: null,
    },
    {
      title: 'Mybnb',
      src: '/mybnb.jpg',
      description: 'Decentralized Airbnb clientside',
      href: null,
    },
    {
      title: 'Nexter',
      src: '/nexter.jpeg',
      description: 'Real estate clientside',
      href: 'https://nexter-ecru.vercel.app',
    },
    {
      title: 'Trillo',
      src: '/trillo.jpeg',
      description: 'Hotel finder clientside',
      href: 'https://trillo-mu-sable.vercel.app',
    },
    {
      title: 'Natours',
      src: '/natours.jpeg',
      description: 'Adventure tours clientside',
      href: 'https://natours-rust-zeta.vercel.app',
    },
  ];

  function renderProjects() {
    return sideProjects.map((project, index) => {
      return <Project key={index} project={project} />;
    });
  }
  function renderPastProjects() {
    return pastProjects.map((project, index) => {
      return <Project key={index} project={project} />;
    });
  }

  return (
    <div>
      <Head>
        <title>Project Gallery · Aaron Nolan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles['projects__main']}>
        <h1 className={styles['projects__main__title']}>Project Gallery</h1>
        <section className={styles['projects__main__section']}>
          <h2 className={styles['projects__main__section__title']}>
            Side projects
          </h2>
          <div className={styles['projects__main__section__grid']}>
            {renderProjects()}
          </div>
        </section>
        <section className={styles['projects__main__section']}>
          <h2 className={styles['projects__main__section__title']}>
            Past projects
          </h2>
          <div className={styles['projects__main__section__grid']}>
            {renderPastProjects()}
          </div>
        </section>
      </main>
    </div>
  );
}

export default Projects;
